import React from "react";
import styles from "./object.module.scss";
import Mailing from "@/components/Mailing/Mailing";
import cn from "classnames";
import Slider from "@/components/Slider/Slider";
import BuildPriceCardLayout from "@/layout/BuildPriceCardLayout/buildPriceCardLayout";
import { buildPriceCard } from "./mock";
import Spacer from "@/components/Spacer/Spacer";
import DevelopersCard from "@/components/DevelopersCard/DevelopersCard";
import Construction from "@/assets/image/construction.svg";
import Cash from "@/assets/image/cash.svg";
import CharacteristicLayout from "@/layout/CharacteristicLayout/characteristicLayout";
import DocumentsLayout from "@/layout/CharacteristicLayout/documentsLayout";
import AboutProject from "@/components/AboutProject/aboutProject";
import TermsOfPurchase from "@/layout/TermsOfPurchase/termsOfPurchase";
import CardsLayout from "@/layout/CardsLayout/cardsLayout";
import fetchersService from "@/services/fetchers.service";
import Head from "next/head";

export default function Object({ data }) {
    console.log("lol", data);

    // const addressArray = Object.keys(data?.addresses).map((key) => ({
    //     name: key,
    //     value: data.addresses[key],
    // }));

    console.log("data?.images", data?.images);
    return (
        <>
            <Head>
                <title>{data?.title} — Asgard </title>
                <meta
                    name="description"
                    content="Generated by create next app"
                />
                <meta
                    name="viewport"
                    content="width=device-width, initial-scale=1"
                />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <div className={styles.header}>
                <div className={styles.contacts}>
                    <div className={styles.title}>
                        <h4 className={styles.descr}>
                            {data?.category?.title}
                        </h4>
                        <h1 className={cn("catalog__title", styles.name)}>
                            {data?.title}
                        </h1>
                    </div>
                    <div className={styles.adress}>
                        <p>Адрес объекта:</p>
                        {/* {Object.values(data?.addresses)?.map((value) => (
                            <p>{value}</p>
                        ))} */}
                        <p>{buildPriceCard[0].adress}</p>
                    </div>
                    <div className={styles.developer}>
                        <div className={styles.developerCard}>
                            <DevelopersCard
                                object={true}
                                color={buildPriceCard[0]?.developer?.color}
                                img={buildPriceCard[0]?.developer?.img}
                                title={data?.developer?.title}
                                wip={data?.developer?.houses_in_process}
                                workDone={data?.developer?.houses_built}
                            />
                        </div>
                        <div className={styles.bottom}>
                            <div className={styles.cash}>
                                <Cash />
                                <p>{buildPriceCard[0]?.items[0]}</p>
                            </div>
                            <div className={styles.construction}>
                                <Construction />
                                <p>{buildPriceCard[0]?.items[1]}</p>
                            </div>
                        </div>
                    </div>
                </div>
                <div className={styles.gallery}>
                    <Slider
                        page={true}
                        buttonsTop={true}
                        thumb={true}
                        img={data?.images}
                    />
                </div>
            </div>
            <Spacer size={83} />
            <BuildPriceCardLayout
                course={buildPriceCard[0]?.course}
                date={buildPriceCard[0]?.date}
                prices={buildPriceCard[0]?.prices}
                quarter={buildPriceCard[0]?.quarter}
                fakePriceCard={buildPriceCard[0]?.fakePriceCard}
                sold={buildPriceCard[0]?.sold}
            />
            <Spacer size={117} />

            <TermsOfPurchase />
            <Spacer size={83} />

            <CharacteristicLayout characteristic={data?.attributes} />
            <Spacer size={83} />

            <DocumentsLayout documents={buildPriceCard[0]?.documents} />
            <Spacer size={55} />

            <CardsLayout
                statusBuilding={true}
                data={buildPriceCard[0]?.constructionStatus}
                title={"статус строительства"}
            />
            <Spacer size={64} />

            <AboutProject text={buildPriceCard[0]?.aboutProject[0]?.text} />
            <Spacer size={75} />

            <CardsLayout
                recomended={true}
                data={buildPriceCard[0]?.recomendation}
                title={"рекомендации"}
            />
            <Spacer size={57} />

            <Mailing name={buildPriceCard[0]?.name} large={true} />
        </>
    );
}

export async function getStaticPaths() {
    const res = await fetchersService.getAll("/flats");
    console.log("----------------");
    console.log(res);
    console.log("----------------");
    const paths = res.data.data.map((flat) => ({
        params: { slug: flat.slug },
    }));
    return { paths, fallback: false };
}

export async function getStaticProps({ params }) {
    const data = await fetchersService
        .getFlats("/flats/view", params.slug)
        .then(({ data }) => {
            return data?.data;
        });

    return { props: { data } };
}
