import tempCard from "@/assets/image/tempCard.png";
import developer from "@/assets/image/developer.png";

export const mockCards = [
    {
        img: tempCard,
        title: "ЖК ПЕРСПЕКТИВА",
        subTitle: "Район Южный",
        repair: true,
        onlyStock: false,
        price: "7.000 $",
        buildings: "1 строится, 3 постоенно",
        seaDistance: false,
        metroDistance: "1 ",
    },
    {
        img: tempCard,
        repair: true,
        onlyStock: false,
        price: "7.000 $",
        buildings: "1 строится, 3 постоенно",
        seaDistance: false,
        metroDistance: "1 ",
        title: "ЖК ПЕРСПЕКТИВА",
        subTitle: "Район Южный",
    },
    {
        img: tempCard,
        repair: true,
        onlyStock: false,
        price: "7.000 $",
        buildings: "1 строится, 3 постоенно",
        seaDistance: "1 ",
        metroDistance: false,
        title: "ЖК ПЕРСПЕКТИВА",
        subTitle: "Район Южный",
    },
    {
        img: tempCard,
        repair: true,
        onlyStock: false,
        price: "7.000 $",
        buildings: "1 строится, 3 постоенно",
        seaDistance: "1 ",
        metroDistance: false,
        title: "ЖК ПЕРСПЕКТИВА",
        subTitle: "Район Южный",
    },
    {
        img: tempCard,
        repair: true,
        onlyStock: false,
        price: "7.000 $",
        buildings: "1 строится, 3 постоенно",
        seaDistance: "1 ",
        metroDistance: false,
        large: true,
        developer: {
            img: developer,
            developerColorBG: "aqua",
        },
        title: "ЖК ПЕРСПЕКТИВА",
        subTitle: "Район Южный",
    },
    {
        img: tempCard,
        repair: true,
        onlyStock: false,
        price: "7.000 $",
        buildings: "1 строится, 3 постоенно",
        seaDistance: "1 ",
        metroDistance: false,
        title: "ЖК ПЕРСПЕКТИВА",
        subTitle: "Район Южный",
    },
    {
        img: tempCard,
        repair: true,
        onlyStock: false,
        price: "7.000 $",
        buildings: "1 строится, 3 постоенно",
        seaDistance: "1 ",
        metroDistance: false,
        title: "ЖК ПЕРСПЕКТИВА",
        subTitle: "Район Южный",
    },
];

export const developers = [
    {
        img: developer,
        title: "DOMO COMPANY",
        workDone: "34 дома сдано",
        wip: "133 дома в процессе",
        color: "#2365af",
    },
    {
        img: developer,
        title: "DOMO COMPANY",
        workDone: "34 дома сдано",
        wip: "133 дома в процессе",
        color: "white",
    },
    {
        img: developer,
        title: "DOMO COMPANY",
        workDone: "34 дома сдано",
        wip: "133 дома в процессе",
        color: "#dfa52d",
    },
    {
        img: developer,
        title: "DOMO COMPANY",
        workDone: "34 дома сдано",
        wip: "133 дома в процессе",
        color: "#2365af",
    },
];

export const mockStockCard = [
    {
        img: tempCard,
        repair: false,
        onlyStock: true,
        stockFrom: "02.03.2000",
        stockTo: "02.03.2000",
        price: "7.000 $",
        buildings: "1 строится, 3 постоенно",
        seaDistance: "1 ",
        metroDistance: false,
        title: "ЖК ПЕРСПЕКТИВА",
        subTitle: "Район Южный",
    },
    {
        img: tempCard,
        repair: false,
        onlyStock: true,
        stockFrom: "02.03.2040",
        stockTo: "02.03.2000",
        price: "7.000 $",
        buildings: "1 строится, 3 постоенно",
        seaDistance: false,
        metroDistance: "40 ",
        title: "Title",
        subTitle: "Район Южный",
    },
    {
        img: tempCard,
        repair: false,
        onlyStock: true,
        stockFrom: "02.03.2000",
        stockTo: "02.03.2000",
        price: "7.000 $",
        buildings: "1 строится, 3 постоенно",
        seaDistance: "1 ",
        metroDistance: false,
        title: "ЖК ПЕРСПЕКТИВА",
        subTitle: "Район Южный",
    },
    {
        img: tempCard,
        repair: false,
        onlyStock: true,
        stockFrom: "02.03.2040",
        stockTo: "02.03.2000",
        price: "7.000 $",
        buildings: "1 строится, 3 постоенно",
        seaDistance: false,
        metroDistance: "40 ",
        title: "Title",
        subTitle: "Район Южный",
    },
    {
        img: tempCard,
        repair: false,
        onlyStock: true,
        stockFrom: "02.03.2000",
        stockTo: "02.03.2000",
        price: "7.000 $",
        buildings: "1 строится, 3 постоенно",
        seaDistance: "1 ",
        metroDistance: false,
        title: "ЖК ПЕРСПЕКТИВА",
        subTitle: "Район Южный",
    },
    {
        img: tempCard,
        repair: false,
        onlyStock: true,
        stockFrom: "02.03.2040",
        stockTo: "02.03.2000",
        price: "7.000 $",
        buildings: "1 строится, 3 постоенно",
        seaDistance: false,
        metroDistance: "40 ",
        title: "Title",
        subTitle: "Район Южный",
    },
];
